### ISSUE TITLE
Nethunter isn't installing

### ISSUE THREAD

**Issue by james123e** [Mr-HotHead/nethunter-termux#1]
Please solve this:
[*] Configuring NetHunter for Termux ...
chmod: cannot access 'kali-armhf/usr/bin/sudo': No such file or directory
![Screenshot_20210524-125914](https://user-images.githubusercontent.com/84703945/119312434-fa436c80-bc8f-11eb-9531-9edcccb0e717.png)

**Comment by Mr-HotHead** [comment]
> Please solve this:
> [*] Configuring NetHunter for Termux ...
> chmod: cannot access 'kali-armhf/usr/bin/sudo': No such file or directory
> ![Screenshot_20210524-125914](https://user-images.githubusercontent.com/84703945/119312434-fa436c80-bc8f-11eb-9531-9edcccb0e717.png)

🧐Once delete and download the OS file again and try.
