### ISSUE TITLE
Doesn't do anything after I run the install script 

### ISSUE THREAD

**Issue by vonkopolo** [Mr-HotHead/nethunter-termux#2]
![Screenshot_20210609-030649_Termux.jpg](https://user-images.githubusercontent.com/34161120/121276877-c7c08300-c8cf-11eb-9b72-b380f9000d45.jpg)

**Comment by Mr-HotHead** [comment]
Maybe your internet is slow or your device storage is full.

**Comment by vonkopolo** [comment]
> ![Screenshot_20210609-030649_Termux.jpg](https://user-images.githubusercontent.com/34161120/121276877-c7c08300-c8cf-11eb-9b72-b380f9000d45.jpg)

Ran apt update && apt upgrade that solved it for me

**Comment by Mr-HotHead** [comment]
> > ![Screenshot_20210609-030649_Termux.jpg](https://user-images.githubusercontent.com/34161120/121276877-c7c08300-c8cf-11eb-9b72-b380f9000d45.jpg)
> 
> Ran apt update && apt upgrade that solved it for me

Literally everyone upgrades the termux packages after they install termux ,how did you thought to install kali Linux without upgrading packages
